INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'NO HAY ASIGNATURA', '0000' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'Administración', 'A1' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ADMINISTRACIÓN II', 'ADM103' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CONTROL DE LA GESTION TOTAL', 'ADM401' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ESTRATEGIA GERENCIAL', 'ADM402' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'FORMULACIÓN Y EVALUACIÓN DE PROYECTOS', 'ADM410' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DISEÑO Y ECOLOGÍA I', 'ARQ211' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DISEÑO ARQUITECTÓNICO II', 'ARQ222' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CAD 2D', 'ARQ241' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ESTRUCTURAS DE CONCRETO I', 'ARQ301' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ESTRUCTURAS DE CONCRETO III', 'ARQ303' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'diseño arquitectónico iii', 'ARQ323' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DISEÑO ARQUITECTÓNICO IV', 'ARQ324' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DISEÑO VI', 'ARQ326' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CAD 3D', 'ARQ342' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CARTOGRAFÍA Y TOPOGRAFÍA', 'ARQ343' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'URBANISMO II', 'ARQ402' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PLANIFICACIÓN URBANA I', 'ARQ403' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DISEÑO ARQUITECTóNICO VIII', 'ARQ428' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PAISAJISMO', 'ARQ429' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'administración de obras', 'ARQ437' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CONSERVACIÓN DE MONUMENTOS', 'ARQ438' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'GESTIóN VIVIENDA POPULAR', 'ARQ439' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PLANIFICACIóN II', 'ARQ504' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROYECTO DE GRADUACIóN FASE I', 'ARQ592' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROYECTO DE GRADUACIóN FASE II', 'ARQ593' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'FOTOGRAFÍA COMERCIAL', 'ART111' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ECOLOGíA', 'BIO202' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'SOCIEDAD HUMANA Y ECOLOGíA', 'BIO203' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ORGANIZACIÓN DE ARCHIVOS', 'CCC302' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGENIERíA DE SOFTWARE', 'CCC406' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DESARROLLO DE APLICACIONES WEB', 'CCC419' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROYECTO DE GRADUACIÓN FASE I', 'CCC593' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROYECTO DE GRADUACIÓN FASE II', 'CCC594' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'Topografía I topograf', 'CIV303' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'Topografía II', 'CIV305' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ESTRUCTURA DE CONCRETO I', 'CIV309' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DISEÑO ESTRUCTURAL I', 'CIV404' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DISEÑO ESTRUCTURAL II', 'CIV406' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGENIERíA SANITARIA I', 'CIV407' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'MATERIALES DE CONSTRUCCIÓN', 'CIV408' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ingenería hidrÁUlica I', 'CIV412' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROYECTO I', 'CIV491' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROYECTO II', 'CIV492' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'VÍAS DE COMUNICACIÓN II', 'CIV504' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'SEMINARIO DE GESTIóN DE PROYECTOS', 'CIV505' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGENIERÍA HIDRÁULICA II', 'CIV506' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'COMUNICACIÓN Y SOCIEDAD', 'COM102' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'COMUNICACIÓN GRÁFICA II', 'COM303' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PRODUCCIóN DE LA PUBLICIDAD', 'COM308' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'creatividad publicitaria', 'COM310' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CAMPAÑAS DE DIVULGACIóN', 'COM311' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'EDICIÓN DE IMPRESOS', 'COM402' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'MULTIMEDIA', 'COM404' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ADMINISTRACIóN DE LA PUBLICIDAD', 'COM405' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'IMAGEN CORPORATIVA', 'COM406' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DISEÑO GRÁFICO Y ANIMACIÓN POR COMPUTADORA', 'COM414' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PRODUCCIÓN DE ARTES GRÁFICAS', 'COM415' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CONTABILIDAD FINANCIERA IV', 'CON207' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CONTABILIDAD FINANCIERA V', 'CON209' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'COSTOS I', 'CON302' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CONTABILIDAD DE COSTOS II', 'CON316' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DERECHO DE SUCESIONES', 'DER202' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DERECHO MERCANTIL I', 'DER209' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DERECHOS HUMANOS', 'DER214' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'LEGISLACIóN FISCAL', 'DER311' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'derecho ambiental', 'DER315' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROMOCIóN Y NEGOCACIóN DE INVERSIONES', 'DER401' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'Práctica Profesional', 'DER421' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ARTES FINALES', 'DGR301' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'NUEVAS TECNOLOGíAS PARA EL DISEÑO GRáFICO', 'DGR303' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'diseño y producción de etiquetas, envases y empaques', 'DGR304' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DISEÑO EDITORIAL', 'DGR400' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'creatividad publicitaria', 'DGR403' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'SISTEMA DE IMPRESIÓN SERIGRÁFICA', 'DGR405' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'SEÑALÉTICA', 'DGR406' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INTRODUCCIÓN A LA TEORÍA MONETARIA', 'ECO301' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'SEMINARIO DE POLÍTICA ECONÓMICA', 'ECO401' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'filosofía', 'FIL101' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'FILOSOFÍA POLÍTICA', 'FIL102' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PRESUPUESTOS', 'FIN303' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ADMINISTRACIÓN BANCARIA', 'FIN306' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'FINANZAS III', 'FIN310' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'GERENCIA FINANCIERA II', 'FIN401' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ADMINISTRACIÓN DEL CRÉDITO', 'FIN414' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PRáCTICA PROFECIONAL', 'FIN593' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'Seguridad e Higiene industrial', 'IND202' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGENIERÍA DE MÉTODOS', 'IND301' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'GESTIóN DE LA CALIDAD', 'IND307' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'SEMINARIO DE GESTIóN DE PROCESOS', 'IND311' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'GESTIóN DE PROCESOS', 'IND312' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CONTROL ESTADÍSTICO DE PROCESOS', 'IND401' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ADMINISTRACIóN DE PROYECTOS', 'IND404' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ADMINISTRACIÓN DE LA TECNOLOGÍA', 'IND406' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'MODELACIÓN DE PROCESOS INDUSTRIALES', 'IND413' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INNOVACIóN Y DESARROLLO DE PRODUCTOS', 'IND418' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'REGULACIÓN AUTOMÁTICA', 'IND513' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROYECTO DE GRADUACIÓN', 'IND594' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'análisis y diseño de sistemas i', 'INF405' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ANáLISIS Y DISEÑO DE SISTEMAS II', 'INF406' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGLéS I', 'ING105' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGLéS II', 'ING106' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGLéS III', 'ING107' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGLéS IV', 'ING108' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGLéS V', 'ING109' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGLéS VI', 'ING110' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGLéS VII', 'ING111' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INGLéS VIII', 'ING112' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'OFIMáTICA I', 'LCC101' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'OFIMáTICA II', 'LCC102' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'OFIMáTICA III', 'LCC103' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'LABORATORIO DE TOPOGRAFíA', 'LCI301' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'LABORATORIO DE PROGRAMACIÓN II', 'LCP105' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'GESTIÓN DE COMPRAS', 'LOG301' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'MATEMÁTICAS NIVELATORIA', 'MAT001' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ESTADÍSTICA I', 'MAT107' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'TERMODINÁMICA', 'MEC300' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'SENSORES Y ACTUADORES', 'MEC306' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'diseño mecatrónico', 'MEC402' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'SISTEMAS MECATRÓNICOS', 'MEC403' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CONTROL LÓGICO PROGRAMABLE', 'MEC406' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'REDES INDUSTRIALES', 'MEC408' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'MANTENIMIENTO DE SISTEMAS HIDRÁULICOS', 'MEC600' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CALDERAS Y GENERADORES DE VAPOR', 'MEC602' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PUBLICIDAD', 'MER203' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INVESTIGACIóN DE MERCADOS I', 'MER204' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'MERCADOTECNIA I', 'MER207' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'mercadotEcnia ii', 'MER312' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PLANEACIóN Y CONTROL DE LA MERCADOTECNIA', 'MER401' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ESTRATEGIAS DE MERCADOTECNIA INTERNACIONAL', 'MER408' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROYECTO DE GRADUACIÓN', 'MER598' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'Matemáticas nivelatoria',	'MM-O 1' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'proyecto 1', 'PG 1'  );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'introducción a la psicología empresarial', 'PSE101' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PSICOLOGíA ORGANIZACIONAL', 'PSE103' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PSICOMETRIA I', 'PSE203' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PSICOLOGíA DEL DESARROLLO HUMANO', 'PSE204' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PSICOLOGIA DE LOS PROCESOS SOCIALES', 'PSE207' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PSICOLOGíA PREVENTIVA', 'PSE210' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PSICOMETRÍA III', 'PSE300' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DESARROLLO Y EVALUACIóN DEL DESEMPEÑO', 'PSE301' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ADMINISTRACION BANCARIA', 'PSE306' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PSICODIAGNóSTICO', 'PSE308' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PSICOLOGíA EDUCATIVA', 'PSE309' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'TéCNICAS TERAPéUTICAS', 'PSE310' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PSICOLOGÍA DE GRUPOS', 'PSE312' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CONSULTORíA EMPRESARIAL', 'PSE404' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'GESTIÓN DE RECURSOS HUMANOS I', 'REH101' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'gerencia de recursos humanos ii', 'REH303' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'RELACIONES PúBLICAS Y PROTOCOLO', 'REL103' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'FORMULACIÓN Y EVALUACIÓN DE PROYECTOS DE COMERCIO EXTERIOR', 'REL312' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROYECTO DE INVESTIGACIÓN', 'REL401' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PROYECTO DE GRADUACIÓN', 'REL492' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'INSTALACIONES ELÉCTRICAS', 'SEL303' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CIRCUITOS II', 'SEL306' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DISEÑO DE SISTEMAS LÓGICOS', 'SEL406' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'SOCIOLOGíA', 'SOC101' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'TALLER DE INTELIGENCIA EMOCIONAL', 'TLL300' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'TALLER TRABAJO EN EQUIPO', 'TLL305' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'TALLER DE SERVICIO AL CLIENTE', 'TLL311' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'GEOGRAFíA NACIONAL DEL TURISMO', 'TUR103' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'TEORíA DEL TURISMO', 'TUR104' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'GEOGRAFíA TURíSTICA UNIVERSAL', 'TUR204' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ADMINISTRACIÓN DE EMPRESAS DE RECREACIÓN', 'TUR206' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ANáLISIS Y CONTROL DE A&B', 'TUR303' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'TURISMO SOSTENIBLE', 'TUR306' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ADMINISTRACIÓN DE OPERACIÓN HOTELERA', 'TUR307' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'PLANIFICACIóN Y ORDENAMIENTO TERRITORIAL', 'TUR401' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'DESARROLLO DE PRODUCTOS TURÍSTICOS', 'TUR403' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'ANIMACIóN TURíSTICA', 'TUR404' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'FERIAS TURÍSTICAS', 'TUR405' );
INSERT INTO `vinculacion`.`classes`(Name, Code) VALUES( 'CONGRESOS Y CONVENCIONES', 'TUR406' );